### ISSUE TITLE
error for landscapes.rds input file

### ISSUE THREAD

**Issue by jhpantel** [project-gen3sis/Simulations#1]
Hello. I am trying to follow the gen3sis Introduction vignette, and when I try the run_simulation command, I receive the following message:

sim <- run_simulation(config = file.path(datapath, "config/config_southamerica.R"),landscape = file.path(datapath, "landscape"), output_directory = tempdir(), call_observer = 1,verbose = 0)
[1] "config found: /Users/jhpantel/Documents/GitHub/ecoevor/R/SAmerica/config/config_southamerica.R"
[1] "landscape found: /Users/jhpantel/Documents/GitHub/ecoevor/R/SAmerica/landscape"
[1] "output directory is: /var/folders/33/1bn95rf573jf03kwqhr9ly200000gn/T//RtmpavmdQQ/config_southamerica"
Error in readRDS(neighbour_file) : unknown input format

Let me know if you can help with this, if there is any issue with the file (which I obtained from the data that accompanies the package): /Library/Frameworks/R.framework/Versions/4.1/Resources/library/gen3sis/extdata/SouthAmerica/landscape

Pardon me if you are not accepting issue reports at this time. I have tried to open this .rds file, and have had no success.

**Comment by ohagen** [comment]
Hi!

I'm afraid that you wont be able to run this input as is if you do not compile the distance matrices either local or full. Have a look at the landscape creation tutorials. I am working on some code to make it easier to compile the distance matrices with an .rds file. 

Let me know if you would like them and I can send it to you over e-mail. My contact you find at hagen.bio, or here when I find some time to make it neat.

The distance files where removed to keep the package size in check according to CRAN policy.

**Comment by jhpantel** [comment]
Hello,

Thank you very much for your response, I see now that 'just' pasting in the landscape files wasn't correct. I have now successfully followed the landscape creation tutorial, and now my simulation following the Introduction vignette is running. Thank you for your help!

**Comment by ohagen** [comment]
Glad it worked.
